Section 2 tasks
js-tasks-ru/js-20200821-3_antonio-kravets pull request #2
Opened 2020-08-26 08:10 UTC by kriffer

2020-08-26 08:16 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
sortStrings
+ should return sorted by "asc" array of strings
+ should return a new sorted array
+ should return sorted by "desc" array of strings
+ should correctly sort language-specific characters
+ should correctly sort strings started from uppercase
```
```diff
pick
+ should return new object with one passed field
+ should return new object with a few passed field
+ should return an empty object if passed fields does not found
```
```diff
omit
+ should return a new object without passed field
+ should return a new object without few passed fields
+ should return initial object if passed fields doesn't found
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-08-26 10:16 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let sortedArr = [];
`sortedArr` не изменяется по ходу программы, поэтому необходимо использовать `const`

2020-08-26 10:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  let temp;
по имени `temp` очень сложно понять что именно вы будете хранить в этой переменной, подумайте над более удачным имененм

2020-08-26 10:19 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  for (let i = 0; i < arr.length; i++) {
Для сортировки массивов в JS есть встроенный метод `sort`,
замените вложенные циклы на этот метод https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

2020-08-26 10:19 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let newObj = {};
`newObj` не изменяется по ходу программы - используйте `const`

2020-08-26 10:21 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    Object.entries(obj).map(([key, value]) => {
Вы используете метод `map` для обхода массива - это семантически неверно.
Метод `map` используется для того чтобы преобразовать исходный массив, поэтому для обычного обхода используйте либо встроенный метод `forEach` либо конструкцию `for...of`

2020-08-26 10:22 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  for (let i = 0; i < fields.length; i++) {
подумайте как избавиться от этого цикла, посмотрите в сторону метода `includes` https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/includes

2020-08-26 10:23 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +    if (!fields.includes(key)) {
отлично 👍  `includes ` это как раз то что нам нужно

2020-08-26 10:23 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let newObj = {};
`newObj` должен быть объявлен через `const`

2020-08-26 10:24 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).map(([key, value]) => {
`map` здесь нужно заменить либо на `forEach` либо на `for...of` - смотри комент выше

2020-08-26 10:25 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-08-26 15:07 UTC, kriffer commented on 02-javascript-data-types/3-omit/index.js
> +  Object.entries(obj).map(([key, value]) => {
thx done!

2020-08-26 15:07 UTC, kriffer commented on 02-javascript-data-types/2-pick/index.js
> +  for (let i = 0; i < fields.length; i++) {
thx done!

2020-08-26 15:07 UTC, kriffer commented on 02-javascript-data-types/2-pick/index.js
> +    Object.entries(obj).map(([key, value]) => {
thx done!

2020-08-26 15:07 UTC, kriffer commented on 02-javascript-data-types/1-sort-strings/index.js
> +  for (let i = 0; i < arr.length; i++) {
thx done!

2020-08-26 15:07 UTC, kriffer commented on 02-javascript-data-types/3-omit/index.js
> +  let newObj = {};
done

2020-08-26 15:09 UTC, jsru commented
@dosandk ping :)

2020-08-27 09:38 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  arr.sort((i, j) => i.localeCompare(j, 'ru', { usage: 'sort', caseFirst: 'upper' }));
метод `arr.sort` изменит исходный массив `arr` - а это крайне нежелательно, другие части кода не ожидают что массив изменится, именно по этому мы возвращаем новый массив

2020-08-27 09:39 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  if (param === 'desc') {
так делать также не следует, нужно сортировать массив сразу в нужном порядке, операцию `reverse` является лишней

2020-08-27 09:40 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +  arr.forEach(function (value) {
для того чтобы скопировать массив используйте следующий способ:

```
const arrCopy = [...arr];
```

2020-08-27 09:41 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  Object.entries(obj).forEach(([key, value]) => {
good 👍

2020-08-27 09:41 UTC, dosandk requested changes
нужно поправить `sortStrings`, остальное - хорошо

2020-08-27 12:03 UTC, jsru commented
@dosandk ping :)

2020-08-28 09:47 UTC, dosandk approved these changes
решения принимаются, обратите внимание на решение `sortStrings` которое будем разбирать на занятии

2020-08-28 09:47 UTC, merged